/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycalculator;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.Point;
import java.awt.TextField;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SpringLayout;
import javax.swing.SpringLayout.Constraints;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import mycalculator.CalculatorObjects;
import mycalculator.CalculatorObjects.AppState;
import static mycalculator.CalculatorObjects.AppState.calculating;
import static mycalculator.CalculatorObjects.AppState.equationing;
import static mycalculator.CalculatorObjects.AppState.graphing;
import mycalculator.CalculatorObjects.EquationState;
import static mycalculator.CalculatorObjects.EquationState.linear;
import mycalculator.CalculatorObjects.FunctionType;
import mycalculator.CalculatorObjects.circleFunction;
import mycalculator.CalculatorObjects.linearFunction;
import mycalculator.CalculatorObjects.myFunction;
import mycalculator.CalculatorObjects.parabolFunction;

/**
 *
 * @author AshCraler
 */
public class CalculatorGUI extends javax.swing.JFrame {

    public class myMouseAdapter extends MouseAdapter{
        int index;
        
        public myMouseAdapter(int i){
            super();
            
            index = i;
        }
        
        @Override
        public void mousePressed(MouseEvent evt){
            delPanelButtonMousePressed(evt, index);
        }
    }
    private Point resultPanelLocation;
    private Point buttonPanelLocation;
    
    private String operationString = "";
    private String result = "";
    private String ans = "0";
    private boolean isRad;
    private float Temp[];
    private CalculatorObjects.linearEquation tempLinear;
    private CalculatorObjects.quadraticEquation tempQuadra;
    private CalculatorObjects.doubleLinearEquation tempDouble;
    
    private AppState appState;
    private EquationState equationState;
    private FunctionType functionType;
    
    ImagePanel doubleLinearImgPanel;
    ImagePanel tripleLinearImgPanel;
    
    JTextField currentField;
    
    GraphicPanel gp;
    FunctionPanel[] functionPanels;
    JScrollPane pane;
    
    int funcCount;
   
    
    public CalculatorGUI() {
        
        initComponents();
        appState = calculating;
        isRad = true;
        this.setLayout(null);
        resultPanelLocation = resultPanel.getLocation();
        buttonPanelLocation = buttonPanel.getLocation();
        
        //dich phai cho textPane
        SimpleAttributeSet attribs = new SimpleAttributeSet();
        StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_RIGHT);
        StyleConstants.setFontSize(attribs, 25);
        StyleConstants.setFontFamily(attribs, "Segoe UI");
        resultTextPane.setParagraphAttributes(attribs, true);
        
        File file = new File("");
        String currentDirectory = file.getAbsolutePath();
        doubleLinearImgPanel = new ImagePanel(currentDirectory + File.separator + "DoubleLinear.png", 175, 75);
        tripleLinearImgPanel = new ImagePanel(currentDirectory + File.separator + "TripleLinear.png", 175, 100);
        equationTypeComboBox.setVisible(false);
        Temp = new float[12];
        
        gp = new GraphicPanel(1100, 750);
        this.add(gp);
        gp.setLocation(300, 0);
        gp.setVisible(false);
        
        functionPanels = new FunctionPanel[30];
        funcCount = 0;
        pane = new JScrollPane(functionPanel, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aLabel = new javax.swing.JLabel();
        x1Label = new javax.swing.JLabel();
        x2Label = new javax.swing.JLabel();
        x3Label = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        y1Label = new javax.swing.JLabel();
        y2Label = new javax.swing.JLabel();
        y3Label = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        z1Label = new javax.swing.JLabel();
        z2Label = new javax.swing.JLabel();
        z3Label = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        aTextField = new javax.swing.JTextField();
        a2TextField = new javax.swing.JTextField();
        a3TextField = new javax.swing.JTextField();
        bTextField = new javax.swing.JTextField();
        b2TextField = new javax.swing.JTextField();
        b3TextField = new javax.swing.JTextField();
        cTextField = new javax.swing.JTextField();
        c2TextField = new javax.swing.JTextField();
        c3TextField = new javax.swing.JTextField();
        d1TextField = new javax.swing.JTextField();
        d2TextField = new javax.swing.JTextField();
        d3TextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        solveButton = new javax.swing.JButton();
        equationPanel = new javax.swing.JPanel();
        addFunctionPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        circleButton = new javax.swing.JButton();
        linearButton = new javax.swing.JButton();
        parabolButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        radiusTextField = new javax.swing.JTextField();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        resultScrollPane = new javax.swing.JScrollPane();
        resultTextPane = new javax.swing.JTextPane();
        buttonPanel = new javax.swing.JPanel();
        dotButton = new javax.swing.JButton();
        num0Button = new javax.swing.JButton();
        num1Button = new javax.swing.JButton();
        num2Button = new javax.swing.JButton();
        num3Button = new javax.swing.JButton();
        num4Button = new javax.swing.JButton();
        num5Button = new javax.swing.JButton();
        num6Button = new javax.swing.JButton();
        num7Button = new javax.swing.JButton();
        num8Button = new javax.swing.JButton();
        num9Button = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        openBracketButton = new javax.swing.JButton();
        closeBracketButton = new javax.swing.JButton();
        piButton = new javax.swing.JButton();
        napierButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        ansButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        mult10powButton = new javax.swing.JButton();
        equationTypeComboBox = new javax.swing.JComboBox<>();
        Deg = new javax.swing.JRadioButton();
        Rad = new javax.swing.JRadioButton();
        menuBar = new javax.swing.JMenuBar();
        modeMenu = new javax.swing.JMenu();
        calculatorMenuItem = new javax.swing.JMenuItem();
        equationMenuItem = new javax.swing.JMenuItem();
        graphicMenuItem = new javax.swing.JMenuItem();

        aLabel.setText("a =");

        x1Label.setText("X + ");

        x2Label.setText("X + ");

        x3Label.setText("X + ");

        bLabel.setText("b =");

        y1Label.setText("Y = ");

        y2Label.setText("Y = ");

        y3Label.setText("Y + ");

        cLabel.setText("c =");

        z1Label.setText("Z = ");

        z2Label.setText("Z = ");

        z3Label.setText("Z = ");

        resultLabel.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N

        aTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aTextFieldFocusGained(evt);
            }
        });

        a2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a2TextFieldFocusGained(evt);
            }
        });

        a3TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a3TextFieldFocusGained(evt);
            }
        });

        bTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bTextFieldFocusGained(evt);
            }
        });

        b2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b2TextFieldFocusGained(evt);
            }
        });

        b3TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b3TextFieldFocusGained(evt);
            }
        });

        cTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cTextFieldFocusGained(evt);
            }
        });

        c2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c2TextFieldFocusGained(evt);
            }
        });

        c3TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c3TextFieldFocusGained(evt);
            }
        });

        d1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                d1TextFieldFocusGained(evt);
            }
        });

        d2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                d2TextFieldFocusGained(evt);
            }
        });

        d3TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                d3TextFieldFocusGained(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        typeLabel.setText("aX + b = 0");

        solveButton.setText("Solve");
        solveButton.setSize(new java.awt.Dimension(100, 30));
        solveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solveButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout equationPanelLayout = new javax.swing.GroupLayout(equationPanel);
        equationPanel.setLayout(equationPanelLayout);
        equationPanelLayout.setHorizontalGroup(
            equationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        equationPanelLayout.setVerticalGroup(
            equationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addFunctionPanel.setPreferredSize(new java.awt.Dimension(250, 120));
        addFunctionPanel.setSize(new java.awt.Dimension(250, 1120));

        javax.swing.GroupLayout addFunctionPanelLayout = new javax.swing.GroupLayout(addFunctionPanel);
        addFunctionPanel.setLayout(addFunctionPanelLayout);
        addFunctionPanelLayout.setHorizontalGroup(
            addFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        addFunctionPanelLayout.setVerticalGroup(
            addFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        functionPanel.setPreferredSize(new java.awt.Dimension(280, 450));
        functionPanel.setSize(new java.awt.Dimension(280, 450));
        functionPanel.setLayout(null);

        circleButton.setText("Circle");
        circleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                circleButtonMousePressed(evt);
            }
        });

        linearButton.setText("Line");
        linearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linearButtonMousePressed(evt);
            }
        });

        parabolButton.setText("Parabol");
        parabolButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                parabolButtonMousePressed(evt);
            }
        });

        drawButton.setText("Draw");
        drawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawButtonMousePressed(evt);
            }
        });

        xLabel.setText("x =");

        yLabel.setText("y = ");

        rLabel.setText("r =");

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backButtonMousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        resultPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        resultPanel.setSize(new java.awt.Dimension(408, 115));

        resultTextPane.setFont(resultTextPane.getFont().deriveFont(resultTextPane.getFont().getStyle() | java.awt.Font.BOLD, 23));
        resultScrollPane.setViewportView(resultTextPane);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        dotButton.setText(".");
        dotButton.setName(""); // NOI18N
        dotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dotButtonMousePressed(evt);
            }
        });

        num0Button.setText("0");
        num0Button.setName(""); // NOI18N
        num0Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num0ButtonMousePressed(evt);
            }
        });

        num1Button.setText("1");
        num1Button.setName(""); // NOI18N
        num1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num1ButtonMousePressed(evt);
            }
        });

        num2Button.setText("2");
        num2Button.setName(""); // NOI18N
        num2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num2ButtonMousePressed(evt);
            }
        });

        num3Button.setText("3");
        num3Button.setName(""); // NOI18N
        num3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num3ButtonMousePressed(evt);
            }
        });

        num4Button.setText("4");
        num4Button.setName(""); // NOI18N
        num4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num4ButtonMousePressed(evt);
            }
        });

        num5Button.setText("5");
        num5Button.setName(""); // NOI18N
        num5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num5ButtonMousePressed(evt);
            }
        });

        num6Button.setText("6");
        num6Button.setName(""); // NOI18N
        num6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num6ButtonMousePressed(evt);
            }
        });

        num7Button.setText("7");
        num7Button.setName(""); // NOI18N
        num7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num7ButtonMousePressed(evt);
            }
        });

        num8Button.setText("8");
        num8Button.setName(""); // NOI18N
        num8Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num8ButtonMousePressed(evt);
            }
        });

        num9Button.setText("9");
        num9Button.setName(""); // NOI18N
        num9Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                num9ButtonMousePressed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.setName(""); // NOI18N
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plusButtonMousePressed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.setName(""); // NOI18N
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minusButtonMousePressed(evt);
            }
        });

        multiButton.setText("x");
        multiButton.setName(""); // NOI18N
        multiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiButtonMousePressed(evt);
            }
        });

        divButton.setText("/");
        divButton.setName(""); // NOI18N
        divButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                divButtonMousePressed(evt);
            }
        });

        delButton.setText("DEL");
        delButton.setName(""); // NOI18N
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delButtonMousePressed(evt);
            }
        });

        resetButton.setText("AC");
        resetButton.setName(""); // NOI18N
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetButtonMousePressed(evt);
            }
        });

        sinButton.setText("sin");
        sinButton.setName(""); // NOI18N
        sinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sinButtonMousePressed(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.setName(""); // NOI18N
        cosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cosButtonMousePressed(evt);
            }
        });

        tanButton.setText("tan");
        tanButton.setName(""); // NOI18N
        tanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tanButtonMousePressed(evt);
            }
        });

        openBracketButton.setText("(");
        openBracketButton.setName(""); // NOI18N
        openBracketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openBracketButtonMousePressed(evt);
            }
        });

        closeBracketButton.setText(")");
        closeBracketButton.setName(""); // NOI18N
        closeBracketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBracketButtonMousePressed(evt);
            }
        });

        piButton.setText("π");
        piButton.setName(""); // NOI18N
        piButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                piButtonMousePressed(evt);
            }
        });

        napierButton.setText("e");
        napierButton.setName(""); // NOI18N
        napierButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                napierButtonMousePressed(evt);
            }
        });

        sqrtButton.setText("√");
        sqrtButton.setName(""); // NOI18N
        sqrtButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sqrtButtonMousePressed(evt);
            }
        });

        powButton.setText("^");
        powButton.setName(""); // NOI18N
        powButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                powButtonMousePressed(evt);
            }
        });

        commaButton.setText(",");
        commaButton.setName(""); // NOI18N
        commaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                commaButtonMousePressed(evt);
            }
        });

        ansButton.setText("Ans");
        ansButton.setName(""); // NOI18N
        ansButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ansButtonMousePressed(evt);
            }
        });

        equalButton.setText("=");
        equalButton.setName(""); // NOI18N
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equalButtonMousePressed(evt);
            }
        });

        mult10powButton.setText("*10^");
        mult10powButton.setName(""); // NOI18N
        mult10powButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mult10powButtonMousePressed(evt);
            }
        });

        equationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aX+b=0", "aX²+bX+c=0", "aX+bY=c", "aX+bY+cZ=d" }));
        equationTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                equationTypeComboBoxItemStateChanged(evt);
            }
        });

        Deg.setText("Deg");
        Deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegActionPerformed(evt);
            }
        });

        Rad.setSelected(true);
        Rad.setText("Rad");
        Rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(num7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(num1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(num4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(num0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult10powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Deg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(napierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Rad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(equationTypeComboBox, 0, 1, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deg)
                    .addComponent(Rad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(napierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mult10powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        modeMenu.setText("MODE");

        calculatorMenuItem.setText("Calculator");
        calculatorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorMenuItemActionPerformed(evt);
            }
        });
        modeMenu.add(calculatorMenuItem);

        equationMenuItem.setText("Equation");
        equationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationMenuItemActionPerformed(evt);
            }
        });
        modeMenu.add(equationMenuItem);

        graphicMenuItem.setText("Graphic");
        graphicMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphicMenuItemActionPerformed(evt);
            }
        });
        modeMenu.add(graphicMenuItem);

        menuBar.add(modeMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input(String str){  
        operationString += str;
        
        switch(appState){
            case calculating:
                resultTextPane.setText(operationString);
                break;
            
            case equationing:
                currentField.setText(operationString);
                break;
                
            case graphing:
                resultTextPane.setText(operationString);
                break;
                
                default:
                    break;
        }
    }
    
    private void output(){
        switch(appState){
            case calculating:
                resultTextPane.setText(operationString);
                break;
            
            case equationing:
                currentField.setText(operationString);
                break;
                
            case graphing:
                resultTextPane.setText(operationString);
                break;
                
                default:
                    break;
        }
    }
    
    private void equationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equationMenuItemActionPerformed
//        this.remove(gp);
        gp.setVisible(false);

        resultPanel.setVisible(false);
        resetButtonMousePressed(null);
        equationTypeComboBox.setVisible(true);
        buttonPanel.setVisible(true);
        buttonPanel.setLocation(resultPanelLocation);
        
        appState = equationing;
        equationState = linear;
        this.setSize(700, 450);
        
        this.add(equationPanel);
        equationPanel.setSize(300, 400);
        equationPanel.setLocation(420, 10);
        showEquationComponent(CalculatorObjects.EquationState.linear);
        
        
        
        System.out.println(buttonPanel.getLocation());
        System.out.println(this.getSize());
    }//GEN-LAST:event_equationMenuItemActionPerformed

    private void showEquationComponent(EquationState eState){
        switch(eState){
            case linear :
                addLabel(typeLabel, 106, 25, 0, 20);
                typeLabel.setText("aX+b=0");
                
                addLabel(aLabel, 25, 25, 10, 50);
                addLabel(bLabel, 25, 25, 10, 80);
                
                addTextField(aTextField, 50, 25, 40, 50);
                addTextField(bTextField, 50, 25, 40, 80);
                
                addButton(solveButton, 100, 30, 70, 120);
                break;
                
            case quadra:
                addLabel(typeLabel, 150, 25, 0, 20);
                typeLabel.setText("aX²+bX+c=0");
                
                addLabel(aLabel, 25, 25, 10, 50);
                addLabel(bLabel, 25, 25, 10, 80);
                addLabel(cLabel, 25, 25, 10, 110);
                
                addTextField(aTextField, 50, 25, 40, 50);
                addTextField(bTextField, 50, 25, 40, 80);
                addTextField(cTextField, 50, 25, 40, 110);
                
                addButton(solveButton, 100, 30, 70, 150);
                break;
                
            case doubleLinear:
                equationPanel.add(doubleLinearImgPanel);
                doubleLinearImgPanel.setSize(175, 75);
                doubleLinearImgPanel.setLocation(0, 20);
                
                //first equation
                addTextField(aTextField, 40, 25, 0, 105);
                addLabel(x1Label, 30, 25, 40, 105);
                addTextField(bTextField, 40, 25, 70, 105);
                addLabel(y1Label, 30, 25, 110, 105);y1Label.setText("Y = ");
                addTextField(cTextField, 50, 25, 150, 105);
                
                //second equation
                addTextField(a2TextField, 40, 25, 0, 135);
                addLabel(x2Label, 30, 25, 40, 135);
                addTextField(b2TextField, 40, 25, 70, 135);
                addLabel(y2Label, 30, 25, 110, 135);y2Label.setText("Y = ");
                addTextField(c2TextField, 50, 25, 150, 135);
                
                addButton(solveButton, 100, 30, 70, 170);
                
                break;
                
            case tripleLinear:
                equationPanel.add(tripleLinearImgPanel);
                tripleLinearImgPanel.setSize(175, 100);
                tripleLinearImgPanel.setLocation(0, 20);
                
                //first equation
                addTextField(aTextField, 40, 25, 0, 125);
                addLabel(x1Label, 30, 25, 40, 125);
                addTextField(bTextField, 40, 25, 70, 125);
                addLabel(y1Label, 30, 25, 110, 125); y1Label.setText("Y + ");
                addTextField(cTextField, 40, 25, 140, 125);
                addLabel(z1Label, 40, 25, 180, 125); 
                addTextField(d1TextField, 50, 25, 220, 125);
                
                //second equation
                addTextField(a2TextField, 40, 25, 0, 155);
                addLabel(x2Label, 30, 25, 40, 155);
                addTextField(b2TextField, 40, 25, 70, 155);
                addLabel(y2Label, 30, 25, 110, 155); y2Label.setText("Y + ");
                addTextField(c2TextField, 40, 25, 140, 155);
                addLabel(z2Label, 40, 25, 180, 155); 
                addTextField(d2TextField, 50, 25, 220, 155);
                
                //third equation
                addTextField(a3TextField, 40, 25, 0, 185);
                addLabel(x3Label, 30, 25, 40, 185);
                addTextField(b3TextField, 40, 25, 70, 185);
                addLabel(y3Label, 30, 25, 110, 185); y3Label.setText("Y + ");
                addTextField(c3TextField, 40, 25, 140, 185);
                addLabel(z3Label, 40, 25, 180, 185); 
                addTextField(d3TextField, 50, 25, 220, 185);
                
                addButton(solveButton, 100, 30, 70, 230);
                break;
                
            default:
                break;
        }
    }
    private void addLabel(JLabel label, int width, int height, int x, int y){
        equationPanel.add(label);
        label.setSize(width, height);
        label.setLocation(x, y);
    }
    
    private void addTextField(JTextField tf, int width, int height, int x, int y){
        equationPanel.add(tf);
        tf.setSize(width, height);
        tf.setLocation(x, y);
    }
    
    private void addButton(JButton bt, int width, int height, int x, int y){
        equationPanel.add(bt);
        bt.setSize(width, height);
        bt.setLocation(x, y);
    }
    
    
    private void calculatorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorMenuItemActionPerformed
//        this.remove(gp);
        gp.setVisible(false);
        
        buttonPanel.setLocation(buttonPanelLocation);
        resultPanel.setVisible(true);
        buttonPanel.setVisible(true);
        equationTypeComboBox.setVisible(false);
        this.remove(equationPanel);
        appState = calculating;
        
        
        this.setSize(420, 600);
        
    }//GEN-LAST:event_calculatorMenuItemActionPerformed

    
    private void num1ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1ButtonMousePressed
        input("1");
    }//GEN-LAST:event_num1ButtonMousePressed

    private void num2ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2ButtonMousePressed
        input("2");
    }//GEN-LAST:event_num2ButtonMousePressed

    private void num3ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3ButtonMousePressed
        input("3");
    }//GEN-LAST:event_num3ButtonMousePressed

    private void plusButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMousePressed
        input("+");
    }//GEN-LAST:event_plusButtonMousePressed

    private void minusButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMousePressed
        input("-");
    }//GEN-LAST:event_minusButtonMousePressed

    private void num4ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4ButtonMousePressed
        input("4");
    }//GEN-LAST:event_num4ButtonMousePressed

    private void num5ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5ButtonMousePressed
        input("5");
    }//GEN-LAST:event_num5ButtonMousePressed

    private void num6ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6ButtonMousePressed
        input("6");
    }//GEN-LAST:event_num6ButtonMousePressed

    private void multiButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiButtonMousePressed
        input("*");
    }//GEN-LAST:event_multiButtonMousePressed

    private void sinButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinButtonMousePressed
        input("sin(");
    }//GEN-LAST:event_sinButtonMousePressed

    private void divButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divButtonMousePressed
        input("/");
    }//GEN-LAST:event_divButtonMousePressed

    private void cosButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosButtonMousePressed
        input("cos(");
    }//GEN-LAST:event_cosButtonMousePressed

    private void tanButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanButtonMousePressed
        input("tan(");
    }//GEN-LAST:event_tanButtonMousePressed

    private void openBracketButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBracketButtonMousePressed
        input("(");
    }//GEN-LAST:event_openBracketButtonMousePressed

    private void closeBracketButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBracketButtonMousePressed
        input(")");
    }//GEN-LAST:event_closeBracketButtonMousePressed

    private void piButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piButtonMousePressed
        input("π");
    }//GEN-LAST:event_piButtonMousePressed

    private void napierButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_napierButtonMousePressed
        input("e");
    }//GEN-LAST:event_napierButtonMousePressed

    private void sqrtButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqrtButtonMousePressed
        input("√");
        
    }//GEN-LAST:event_sqrtButtonMousePressed

    private void powButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powButtonMousePressed
        input("pow(");
    }//GEN-LAST:event_powButtonMousePressed

    private void commaButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commaButtonMousePressed
        input(",");
    }//GEN-LAST:event_commaButtonMousePressed

    private void delButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMousePressed
        operationString = operationString.substring(0, operationString.length() - 1);
        output();
    }//GEN-LAST:event_delButtonMousePressed

    private void resetButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMousePressed
        operationString = "";
        output();
    }//GEN-LAST:event_resetButtonMousePressed

    private void num7ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7ButtonMousePressed
        input("7");
    }//GEN-LAST:event_num7ButtonMousePressed

    private void num8ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8ButtonMousePressed
        input("8");
    }//GEN-LAST:event_num8ButtonMousePressed

    private void num9ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9ButtonMousePressed
        input("9");
    }//GEN-LAST:event_num9ButtonMousePressed

    private void ansButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ansButtonMousePressed
        input("Ans");
    }//GEN-LAST:event_ansButtonMousePressed

    private void equalButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMousePressed
        if(isRad)
            result = CalculatorObjects.Operation.equal(operationString.replaceAll("Ans", String.valueOf(ans)));
        else{
            result = CalculatorObjects.Operation.equal(operationString.replaceAll("Ans", String.valueOf(ans)).replaceAll("sin\\(", "sin(π/180*").replaceAll("cos\\(", "cos(π/180*").replaceAll("tan\\(", "tan(π/180*"));
        }
        ans = result;
        if(appState != equationing)
            resultTextPane.setText(operationString + "\n" + result);
        else{
            currentField.setText(result);
        }
    }//GEN-LAST:event_equalButtonMousePressed

    private void dotButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMousePressed
        input(".");
    }//GEN-LAST:event_dotButtonMousePressed

    private void mult10powButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mult10powButtonMousePressed
        input("*pow(10,");
    }//GEN-LAST:event_mult10powButtonMousePressed

    private void num0ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0ButtonMousePressed
        input("0");
    }//GEN-LAST:event_num0ButtonMousePressed

    private void equationTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_equationTypeComboBoxItemStateChanged
        switch(String.valueOf(equationTypeComboBox.getSelectedItem())){
            case "aX+b=0":
                equationState = EquationState.linear;
                
                equationPanel.removeAll();
                showEquationComponent(EquationState.linear);
                equationPanel.repaint();
                
                break;
                
            case "aX²+bX+c=0":
                equationState = EquationState.quadra;
                
                equationPanel.removeAll();
                showEquationComponent(EquationState.quadra);
                equationPanel.repaint();
                
                break;
                
            case "aX+bY=c":
                equationState = EquationState.doubleLinear;
                
                equationPanel.removeAll();
                showEquationComponent(EquationState.doubleLinear);
                equationPanel.repaint();
                
                break;
                
            case "aX+bY+cZ=d":
                equationState = EquationState.tripleLinear;
                
                equationPanel.removeAll();
                showEquationComponent(EquationState.tripleLinear);
                equationPanel.repaint();
                
                break;
                
            default:
                    break;
        }
    }//GEN-LAST:event_equationTypeComboBoxItemStateChanged

    private void graphicMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphicMenuItemActionPerformed
        appState = graphing;
        
        equationTypeComboBox.setVisible(false);
        equationPanel.removeAll();
        this.remove(equationPanel);
        
        resultPanel.setVisible(false);
        buttonPanel.setLocation(buttonPanelLocation);
        buttonPanel.setVisible(false);
        
        
        this.setSize(1200, 600);
        
        gp.setVisible(true);
        
        this.add(functionPanel);
        functionPanel.setLocation(0, 150);
        functionPanel.setSize(280, 450);
        functionPanel.setPreferredSize(new Dimension(280, 450));
        
        
        functionPanel.add(pane, BorderLayout.EAST);
        pane.setPreferredSize(new Dimension(280, 450));
        this.add(pane);
        
        this.add(addFunctionPanel);
        addFunctionPanel.setLocation(10, 30);
        addFunctionPanel.setSize(290, 120);
        addFunctionPanel.setLayout(null);
        
        addFunctionPanel.add(circleButton);
        circleButton.setSize(80, 30);
        circleButton.setLocation(5, 30);
        
        addFunctionPanel.add(linearButton);
        linearButton.setSize(80, 30);
        linearButton.setLocation(100, 30);
        
        addFunctionPanel.add(parabolButton);
        parabolButton.setSize(80, 30);
        parabolButton.setLocation(195, 30);
        
        addFunctionPanel.add(drawButton);
        drawButton.setSize(80, 30);
        drawButton.setLocation(150, 70);
        drawButton.setVisible(false);
        
        addFunctionPanel.add(backButton);
        backButton.setSize(80, 30);
        backButton.setLocation(50, 70);
        backButton.setVisible(false);
        
    }//GEN-LAST:event_graphicMenuItemActionPerformed

    private void RadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadActionPerformed
        
        if (Rad.isSelected()){
            isRad = true;
            Deg.setSelected(false);
        }
    }//GEN-LAST:event_RadActionPerformed

    private void aTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aTextFieldFocusGained
        operationString = "";
        currentField = aTextField;
    }//GEN-LAST:event_aTextFieldFocusGained

    private void bTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bTextFieldFocusGained
        operationString = "";
        currentField = bTextField;
    }//GEN-LAST:event_bTextFieldFocusGained

    private void a2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a2TextFieldFocusGained
        operationString = "";
        currentField = a2TextField;
    }//GEN-LAST:event_a2TextFieldFocusGained

    private void a3TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a3TextFieldFocusGained
        operationString = "";
        currentField = a3TextField;
    }//GEN-LAST:event_a3TextFieldFocusGained

    private void b2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b2TextFieldFocusGained
        operationString = "";
        currentField = b2TextField;
    }//GEN-LAST:event_b2TextFieldFocusGained

    private void b3TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b3TextFieldFocusGained
        operationString = "";
        currentField = b3TextField;
    }//GEN-LAST:event_b3TextFieldFocusGained

    private void cTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cTextFieldFocusGained
        operationString = "";
        currentField = cTextField;
    }//GEN-LAST:event_cTextFieldFocusGained

    private void c2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2TextFieldFocusGained
        operationString = "";
        currentField = c2TextField;
    }//GEN-LAST:event_c2TextFieldFocusGained

    private void c3TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c3TextFieldFocusGained
        operationString = "";
        currentField = c3TextField;
    }//GEN-LAST:event_c3TextFieldFocusGained

    private void d1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d1TextFieldFocusGained
        operationString = "";
        currentField = d1TextField;
    }//GEN-LAST:event_d1TextFieldFocusGained

    private void d2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d2TextFieldFocusGained
        operationString = "";
        currentField = d2TextField;
    }//GEN-LAST:event_d2TextFieldFocusGained

    private void d3TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d3TextFieldFocusGained
        operationString = "";
        currentField = d3TextField;
    }//GEN-LAST:event_d3TextFieldFocusGained

    private void solveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveButtonMouseClicked
        switch(equationState){
            case linear:
                Temp[0] = Float.parseFloat(CalculatorObjects.Operation.equal(aTextField.getText()));
                Temp[1] = Float.parseFloat(CalculatorObjects.Operation.equal(bTextField.getText()));
                
                tempLinear = new CalculatorObjects.linearEquation(Temp[0], Temp[1]);
                if(tempLinear.isSolvable){
                    resultLabel.setText("X = " + String.valueOf(tempLinear.getSolution()));
                }else
                    resultLabel.setText("Phuong trinh nay vo nghiem!");
                
                addLabel(resultLabel, 100, 30, 50, 180);
                break;
                
            case quadra:
                Temp[0] = Float.parseFloat(CalculatorObjects.Operation.equal(aTextField.getText()));
                Temp[1] = Float.parseFloat(CalculatorObjects.Operation.equal(bTextField.getText()));
                Temp[2] = Float.parseFloat(CalculatorObjects.Operation.equal(cTextField.getText()));
                
                tempQuadra = new CalculatorObjects.quadraticEquation(Temp[0], Temp[1], Temp[2]);
                
                if(tempQuadra.isSolvable){
                    if(tempQuadra.isSingleSolution)
                        resultLabel.setText(CalculatorObjects.convertToMultiline("Phuong trinh co nghiem kep: \nX1 = X2 = " + String.valueOf(tempQuadra.getSolutions()[0])));
                    else
                        resultLabel.setText(CalculatorObjects.convertToMultiline("Phuong trinh co 2 nghiem phan biet: \nX1 = " + String.valueOf(tempQuadra.getSolutions()[0]) + "\nX2 = "+ String.valueOf(tempQuadra.getSolutions()[1])));
                }
                else
                    resultLabel.setText("Phuong trinh nay vo nghiem!");
                
                addLabel(resultLabel, 150, 150, 50, 180);
                break;
                
            case doubleLinear:
                Temp[0] = Float.parseFloat(CalculatorObjects.Operation.equal(aTextField.getText()));
                Temp[1] = Float.parseFloat(CalculatorObjects.Operation.equal(bTextField.getText()));
                Temp[2] = Float.parseFloat(CalculatorObjects.Operation.equal(cTextField.getText()));
                Temp[3] = Float.parseFloat(CalculatorObjects.Operation.equal(a2TextField.getText()));
                Temp[4] = Float.parseFloat(CalculatorObjects.Operation.equal(b2TextField.getText()));
                Temp[5] = Float.parseFloat(CalculatorObjects.Operation.equal(c2TextField.getText()));
                
                tempDouble = new CalculatorObjects.doubleLinearEquation(Temp[0], Temp[1], Temp[2], Temp[3], Temp[4], Temp[5]);
                
                switch(tempDouble.getState()){
                    case vonghiem:
                        resultLabel.setText("He phuong trinh vo nghiem!");
                        break;
                        
                    case nghiemdon:
                        resultLabel.setText(CalculatorObjects.convertToMultiline("He phuong trinh co nghiem duy nhat la: \nX = " + tempDouble.getX() + "\nY = " + tempDouble.getY()));
                        break;
                    
                    case vosonghiem:
                        resultLabel.setText("He phuong trinh vo so nghiem!");
                        break;
                        
                    default:
                        break;
                }
                
                addLabel(resultLabel, 250, 150, 20, 180);
                break;
                
            case tripleLinear:
                break;
                
            default:
                break;
        }
        
        
        
        
        
    }//GEN-LAST:event_solveButtonMouseClicked

    private void DegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegActionPerformed
        if(Rad.isSelected()){
            isRad = false;
            Rad.setSelected(false);
        }
    }//GEN-LAST:event_DegActionPerformed

    private void circleButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_circleButtonMousePressed
        circleButton.setVisible(false);
        linearButton.setVisible(false);
        parabolButton.setVisible(false);
        drawButton.setVisible(true);
        backButton.setVisible(true);
        
        addFunctionPanel.add(xLabel);
        xLabel.setSize(25, 25);
        xLabel.setLocation(0, 30);
        xLabel.setText("x =");
        
        addFunctionPanel.add(aTextField);
        aTextField.setSize(50, 25);
        aTextField.setLocation(25, 30);
        aTextField.setText("");
        
        addFunctionPanel.add(yLabel);
        yLabel.setSize(35, 25);
        yLabel.setLocation(80, 30);
        yLabel.setText(", y =");
        
        addFunctionPanel.add(bTextField);
        bTextField.setSize(50, 25);
        bTextField.setLocation(115, 30);
        bTextField.setText("");
        
        addFunctionPanel.add(rLabel);
        rLabel.setSize(25, 25);
        rLabel.setLocation(175, 30);
        
        addFunctionPanel.add(radiusTextField);
        radiusTextField.setSize(50, 25);
        radiusTextField.setLocation(200, 30);
        radiusTextField.setText("");
        
        functionType = FunctionType.circle;
        
    }//GEN-LAST:event_circleButtonMousePressed

    private void linearButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linearButtonMousePressed
        circleButton.setVisible(false);
        linearButton.setVisible(false);
        parabolButton.setVisible(false);
        drawButton.setVisible(true);
        backButton.setVisible(true);
        
        addFunctionPanel.add(xLabel);
        xLabel.setSize(25, 25);
        xLabel.setLocation(0, 30);
        xLabel.setText("a =");
        
        addFunctionPanel.add(aTextField);
        aTextField.setSize(50, 25);
        aTextField.setLocation(20, 30);
        aTextField.setText("");
        
        addFunctionPanel.add(yLabel);
        yLabel.setSize(35, 25);
        yLabel.setLocation(85, 30);
        yLabel.setText(", b =");
        
        addFunctionPanel.add(bTextField);
        bTextField.setSize(50, 25);
        bTextField.setLocation(115, 30);
        bTextField.setText("");
        
        functionType = FunctionType.linear;
    }//GEN-LAST:event_linearButtonMousePressed

    
    private void addFP(FunctionPanel fp, int x, int y){
//        this.add(fp);
        functionPanel.add(fp);
        fp.setSize(280, 100);
        fp.setLocation(x, y);
        fp.setLayout(null);
        
        JButton delPanelButton = new JButton("Delete");
        delPanelButton.addMouseListener(new myMouseAdapter(fp.index));
        
        
        fp.add(delPanelButton);
        delPanelButton.setSize(80, 30);
        delPanelButton.setLocation(200, 5);
        
    }
    
    private void delPanelButtonMousePressed(MouseEvent evt, int index) {

        gp.removeFunction(index);
        
        for(int i = index; i < funcCount - 1; i++){

            functionPanels[i].changeTo(functionPanels[i+1]);
//            functionPanels[i].setLocation(5, 150 + 100*i);
            functionPanels[i].setLocation(5, 10 + 100*i);
        }

//        this.remove(functionPanels[funcCount - 1]);
        functionPanel.remove(functionPanels[funcCount - 1]);
        functionPanels[funcCount - 1] = null;
        
        funcCount--;
        
        repaint();
    }
    
    private void drawButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawButtonMousePressed
        switch(functionType){
            case linear:
                if(aTextField.getText() == "" || bTextField.getText() == ""){
                    JPanel panel = (JPanel) getContentPane();
                    JOptionPane.showMessageDialog(panel, "Vui long nhap cac he so hop le!","Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                    
                linearFunction lF = new linearFunction(Float.parseFloat(aTextField.getText()), Float.parseFloat(bTextField.getText()));
                
                gp.addFunction(lF);
                
                functionPanels[funcCount] = new FunctionPanel(lF, funcCount, gp);
                
//                addFP(functionPanels[funcCount], 5, 150 + 100*funcCount);
                addFP(functionPanels[funcCount], 5, 10 + 100*funcCount);
                funcCount++;
                
                break;
                
            case circle:
                if(aTextField.getText() == "" || bTextField.getText() == "" || radiusTextField.getText() == ""){
                    JPanel panel = (JPanel) getContentPane();
                    JOptionPane.showMessageDialog(panel, "Vui long nhap cac he so hop le!", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                circleFunction cF = new circleFunction(Float.parseFloat(aTextField.getText()), Float.parseFloat(bTextField.getText()), Float.parseFloat(radiusTextField.getText()));
                
                gp.addFunction(cF);
                
                functionPanels[funcCount] = new FunctionPanel(cF, funcCount, gp);
                
//                addFP(functionPanels[funcCount], 5, 150 + 100*funcCount);
                addFP(functionPanels[funcCount], 5, 10 + 100*funcCount);

                funcCount++;
                break;
            case parabol:
                if(aTextField.getText() == "" || bTextField.getText() == "" || cTextField.getText() == ""){
                    JPanel panel = (JPanel) getContentPane();
                    JOptionPane.showMessageDialog(panel, "Vui long nhap cac he so hop le!", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                parabolFunction pF = new parabolFunction(Float.parseFloat(aTextField.getText()), Float.parseFloat(bTextField.getText()), Float.parseFloat(cTextField.getText()));
                
                gp.addFunction(pF);
                
                functionPanels[funcCount] = new FunctionPanel(pF, funcCount, gp);
                
//                addFP(functionPanels[funcCount], 5, 150 + 100*funcCount);
                addFP(functionPanels[funcCount], 5, 10 + 100*funcCount);

                funcCount++;
                break;
            
            default:
                break;
        }
        
        backButtonMousePressed(evt);
    }//GEN-LAST:event_drawButtonMousePressed

    private void backButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMousePressed
        addFunctionPanel.remove(aTextField);
        addFunctionPanel.remove(bTextField);
        addFunctionPanel.remove(radiusTextField);
        addFunctionPanel.remove(cTextField);
        addFunctionPanel.remove(xLabel);
        addFunctionPanel.remove(yLabel);
        addFunctionPanel.remove(rLabel);
        addFunctionPanel.remove(cLabel);
       
        drawButton.setVisible(false);
        backButton.setVisible(false);
        
        circleButton.setVisible(true);
        linearButton.setVisible(true);
        parabolButton.setVisible(true);
        repaint();
    }//GEN-LAST:event_backButtonMousePressed

    private void parabolButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parabolButtonMousePressed
        circleButton.setVisible(false);
        linearButton.setVisible(false);
        parabolButton.setVisible(false);
        drawButton.setVisible(true);
        backButton.setVisible(true);
        
        addFunctionPanel.add(xLabel);
        xLabel.setSize(25, 25);
        xLabel.setLocation(0, 30);
        xLabel.setText("a =");
        
        addFunctionPanel.add(aTextField);
        aTextField.setSize(50, 25);
        aTextField.setLocation(25, 30);
        aTextField.setText("");
        
        addFunctionPanel.add(yLabel);
        yLabel.setSize(35, 25);
        yLabel.setLocation(80, 30);
        yLabel.setText(", b =");
        
        addFunctionPanel.add(bTextField);
        bTextField.setSize(50, 25);
        bTextField.setLocation(115, 30);
        bTextField.setText("");
        
        addFunctionPanel.add(cLabel);
        cLabel.setSize(25, 25);
        cLabel.setLocation(175, 30);
        
        addFunctionPanel.add(cTextField);
        cTextField.setSize(50, 25);
        cTextField.setLocation(200, 30);
        cTextField.setText("");
        
        functionType = FunctionType.parabol;
        
    }//GEN-LAST:event_parabolButtonMousePressed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        gp.setSize(900, this.getHeight() - 50);
        functionPanel.setSize(300, this.getHeight()-100);
        repaint();
    }//GEN-LAST:event_formComponentResized
   
    /*
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Deg;
    private javax.swing.JRadioButton Rad;
    private javax.swing.JTextField a2TextField;
    private javax.swing.JTextField a3TextField;
    private javax.swing.JLabel aLabel;
    private javax.swing.JTextField aTextField;
    private javax.swing.JPanel addFunctionPanel;
    private javax.swing.JButton ansButton;
    private javax.swing.JTextField b2TextField;
    private javax.swing.JTextField b3TextField;
    private javax.swing.JLabel bLabel;
    private javax.swing.JTextField bTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextField c2TextField;
    private javax.swing.JTextField c3TextField;
    private javax.swing.JLabel cLabel;
    private javax.swing.JTextField cTextField;
    private javax.swing.JMenuItem calculatorMenuItem;
    private javax.swing.JButton circleButton;
    private javax.swing.JButton closeBracketButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JTextField d1TextField;
    private javax.swing.JTextField d2TextField;
    private javax.swing.JTextField d3TextField;
    private javax.swing.JButton delButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton drawButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JMenuItem equationMenuItem;
    private javax.swing.JPanel equationPanel;
    private javax.swing.JComboBox<String> equationTypeComboBox;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JMenuItem graphicMenuItem;
    private javax.swing.JButton linearButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton minusButton;
    private javax.swing.JMenu modeMenu;
    private javax.swing.JButton mult10powButton;
    private javax.swing.JButton multiButton;
    private javax.swing.JButton napierButton;
    private javax.swing.JButton num0Button;
    private javax.swing.JButton num1Button;
    private javax.swing.JButton num2Button;
    private javax.swing.JButton num3Button;
    private javax.swing.JButton num4Button;
    private javax.swing.JButton num5Button;
    private javax.swing.JButton num6Button;
    private javax.swing.JButton num7Button;
    private javax.swing.JButton num8Button;
    private javax.swing.JButton num9Button;
    private javax.swing.JButton openBracketButton;
    private javax.swing.JButton parabolButton;
    private javax.swing.JButton piButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton powButton;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextField radiusTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTextPane resultTextPane;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton solveButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel x1Label;
    private javax.swing.JLabel x2Label;
    private javax.swing.JLabel x3Label;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel y1Label;
    private javax.swing.JLabel y2Label;
    private javax.swing.JLabel y3Label;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel z1Label;
    private javax.swing.JLabel z2Label;
    private javax.swing.JLabel z3Label;
    // End of variables declaration//GEN-END:variables

    

}
